# file: roles/api/tasks/main.yml
---
- name: Install git
  apt: pkg={{item}} state=installed
  with_items:
    - git-core
    - build-essential

- git: repo={{ git_repo }} dest='{{ api_dir }}' version={{git_version}} force=yes
  become: yes
  become_user: "{{ ansible_ssh_user }}"

#Backend
- name: Install server node packages
  npm: path={{ api_dir }}/server state=latest
  become: yes
  become_user: "{{ ansible_ssh_user }}"

- name: Copy init script
  template: src=api.conf.j2 dest=/etc/init/api.conf mode=0640 owner=root group=root
  notify:
    - restart api

- name: Copy server config
  template: src=config.json.j2 dest={{ api_dir }}/server/config/{{ node_env }}.json
  notify:
    - restart api
  sudo: yes

- command: npm run build
  args:
    chdir: "{{ api_dir }}/server"
  become: yes
  become_user: "{{ ansible_ssh_user }}"

- command: npm run doc
  args:
    chdir: "{{ api_dir }}/server"
  become: yes
  become_user: "{{ ansible_ssh_user }}"

#Frontend
- name: Copy client config
  template: src=config.js.j2 dest={{ api_dir }}/client/src/app/config.js
  sudo: yes

- name: Install client node packages
  npm: path={{ api_dir }}/client state=latest
  become: yes
  become_user: "{{ ansible_ssh_user }}"

- command: npm run build
  args:
    chdir: "{{ api_dir }}/client"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
