---

nginx_env:
 RUNLEVEL: 1

nginx_installation_types_using_service: ["packages", "configuration-only"]

nginx_is_el: "{{ ansible_distribution in ['RedHat', 'CentOS'] }}"

nginx_http_default_params:
  - sendfile "on"
  - tcp_nopush "on"
  - tcp_nodelay "on"
  - keepalive_timeout "65"
  - access_log "{{nginx_log_dir}}/access.log"
  - "error_log {{nginx_log_dir}}/error.log {{nginx_error_log_level}}"
  - server_tokens off
  - types_hash_max_size 2048
