---
galaxy_info:
  author: "DAUPHANT Julien"
  license: BSD
  min_ansible_version: 1.4
  platforms:
   - name: EL
     versions:
      - 5
      - 6
   - name: Fedora
     versions:
      - 16
      - 17
      - 18
      - 19
      - 20
   - name: opensuse
     versions:
      - 13.1
      - 13.2
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
      - trusty
   - name: FreeBSD
     versions:
      - 10
  categories:
   - web
allow_duplicates: yes
dependencies: []

