# file: postgresql/tasks/extensions/dev_headers.yml

- name: PostgreSQL | Extensions | Make sure the development headers are installed | Debian
  apt:
    name: libpq-dev
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the development headers are installed | RedHat
  yum: "name={{ item }} state=present update_cache=yes"
  with_items:
    - "postgresql{{ postgresql_version_terse }}-libs"
    - "postgresql{{ postgresql_version_terse }}-devel"
  when: ansible_os_family == "RedHat"
  notify:
    - restart postgresql
