# file: postgresql/tasks/extensions/postgis.yml

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items:
    - libgeos-c1
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_ext_postgis_version}}"
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_ext_postgis_version}}-scripts"
  notify:
    - restart postgresql
