---
- name: debian | adding RabbitMQ public GPG key to the apt repo
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: debian | adding RabbitMQ repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' update_cache=no state=present

- name: debian | installing RabbitMQ server
  apt: name={{ item }} state=present
  with_items:
    - rabbitmq-server

- name: debian | enabling the RabbitMQ Management Console
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

- name: debian | ensuring that the RabbitMQ service is running
  service: name=rabbitmq-server state=started enabled=yes
