# tasks file for ansible-rabbitmq
- include: debian.yml
  when: ansible_os_family == "Debian"

- name: checking to see if already clustered
  stat: path=/etc/rabbitmq/clustered
  register: clustered

- include: rabbitmq_clustering.yml
  when: enable_rabbitmq_clustering and (clustered.stat.exists != True)

- include: rabbitmq_ha_config.yml
  when: config_rabbitmq_ha and enable_rabbitmq_clustering
