env_name: dev
user: vagrant
home: /home/vagrant
node_env: development
website_url: "http://localhost:8000"
http_port: 8000
dbname: "main"
dbuser: "postgres"
dbpassword: "password"
mail_service: Mailgun
mail_from: "StarHackIt Vagrant <notification-vagrant@starhack.it>"
mail_user:
mail_password:
facebook_client_id:
facebook_client_secret:
google_analytics:
