env_name: dev
user: vagrant
home: /home/vagrant
node_env: development
website_url: "http://localhost:8000"
mail_service: Mailgun
mail_user:
mail_password:
facebook_client_id: 
facebook_client_secret:
